
name: Package

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/gitignore'
  workflow_dispatch:

jobs:
  upload-ndk-win:
    runs-on: [ self-hosted, Windows, X64, w10-1344 ]
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - name: Find NDK SHA
      run: |
        $INWORLD_NDK_SHA=(git submodule status).Trim().Split()[0]
        echo $INWORLD_NDK_SHA
        Add-Content -Path ${env:GITHUB_ENV} -Value "INWORLD_NDK_SHA=$INWORLD_NDK_SHA"
    - uses: actions/cache/restore@v3
      id: ndk-cache-win64
      with:
        path: InworldAI\inworld-ndk\build\Package
        key: ${{ runner.OS }}-ndk-cache-Win64-${{ env.INWORLD_NDK_SHA }}
        fail-on-cache-miss: true
    - uses: actions/upload-artifact@v3
      with:
        name: NDK-Source
        path: |
          InworldAI\inworld-ndk\build\Package
          !InworldAI\inworld-ndk\build\Package\lib
    - uses: actions/upload-artifact@v3
      with:
        name: Win-NDK-lib
        path: InworldAI\inworld-ndk\build\Package\lib\Win64
  
  upload-ndk-mac:
    runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - name: Find NDK SHA
      run: |
        INWORLD_NDK_SHA=$(git submodule status | cut -d " " -f 2)
        echo $INWORLD_NDK_SHA
        echo "INWORLD_NDK_SHA=$INWORLD_NDK_SHA" >> $GITHUB_ENV
    - uses: actions/cache/restore@v3
      id: ndk-cache-mac
      with:
        path: InworldAI/inworld-ndk/build/Package
        key: ${{ runner.OS }}-ndk-cache-Mac-${{ env.INWORLD_NDK_SHA }}
        fail-on-cache-miss: true
    - uses: actions/upload-artifact@v3
      with:
        name: Mac-NDK-lib
        path: InworldAI/inworld-ndk/build/Package/lib/Mac
  
  upload-ndk-ios:
    runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - name: Find NDK SHA
      run: |
        INWORLD_NDK_SHA=$(git submodule status | cut -d " " -f 2)
        echo $INWORLD_NDK_SHA
        echo "INWORLD_NDK_SHA=$INWORLD_NDK_SHA" >> $GITHUB_ENV
    - uses: actions/cache/restore@v3
      id: ndk-cache-ios
      with:
        path: InworldAI/inworld-ndk/build/Package
        key: ${{ runner.OS }}-ndk-cache-iOS-${{ env.INWORLD_NDK_SHA }}
        fail-on-cache-miss: true
    - uses: actions/upload-artifact@v3
      with:
        name: iOS-NDK-lib
        path: InworldAI/inworld-ndk/build/Package/lib/iOS

  package:
    runs-on: ubuntu-latest
    needs: [ upload-ndk-win, upload-ndk-mac, upload-ndk-ios ]
    steps:
      - uses: actions/checkout@v2
      - name: git-update-dependecies
        run: git submodule update --init --recursive
      - uses: actions/download-artifact@v3
        with:
          name: NDK-Source
          path: InworldAI/Source/ThirdParty/Inworld
      - uses: actions/download-artifact@v3
        with:
          name: Win-NDK-lib
          path: InworldAI/Source/ThirdParty/Inworld/lib/Win64
      - uses: actions/download-artifact@v3
        with:
          name: Mac-NDK-lib
          path: InworldAI/Source/ThirdParty/Inworld/lib/Mac
      - uses: actions/download-artifact@v3
        with:
          name: iOS-NDK-lib
          path: InworldAI/Source/ThirdParty/Inworld/lib/iOS
      - uses: actions/upload-artifact@v3
        with:
          name: inworld-unreal-sdk
          path: |
            InworldAI
            !InworldAI/inworld-ndk
            InworldMetahuman
            InworldRPM
